plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

group = 'fr.g123k.deviceapps'
version = '1.0-SNAPSHOT'

android {
    namespace 'fr.g123k.deviceapps'
    compileSdk = 34

    defaultConfig {
        minSdk = 16
        targetSdk = 33
    }

    lint {
        disable 'InvalidPackage'
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.9.1'
}
